### ISSUE TITLE
Event titles flow outside of element and overlaps with other events in timeline month view when event includes a start time

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#529]
The events are one day 

https://codepen.io/acerix/pen/MRQZmE?editors=0010

Reported in https://fullcalendar.freshdesk.com/a/tickets/808

**Comment by acerix** [comment]
Also reported in https://fullcalendar.freshdesk.com/a/tickets/828

**Comment by harohl** [comment]
I need a fix or work-around for this ASAP.  I cannot roll out the upgrade of full calendar with jumbled titles, and I cannot exclude the event start on the views with 1 day time slots.
I noticed that hovering over the cells fixed the text.  I have not figured out why yet, but this should help to fix or suggest a work-around.

**Comment by arshaw** [comment]
This is a legit bug. It's being caused by the code that does that title "following" (where an event's title stays in view even when it's being scrolled out of the view pane). It happens only when there's a visible event time. This bug we introduced in v4 when we started relying on the browser's native `position: sticky`.

I still need to think of the best CSS solution to solve this problem. It's a bit tricky. But in the meantime I'll offer a workaround.

https://codepen.io/arshaw/pen/KYEeao?editors=0110

```css
.fc-resourceTimelineMonth-view .fc-timeline-event .fc-content {
  overflow: hidden;
}

.fc-resourceTimelineMonth-view .fc-timeline-event .fc-title {
  position: static !important; /* undo sticky */
}
```

This CSS will fix the problem, though it will prevent the nice "title following" behavior. It is scoped to a single view (`resourceTimelineMonth`). If you want it to apply to all timeline view's simply remove the `.fc-resourceTimelineMonth-view` part of the selector.
